#!/usr/bin/env node
// CodeGov PR Scanner — self-contained, zero dependencies
// Detects AI-authored commits in a PR and posts a summary comment.

const { execSync } = require("child_process");

// ── Detection Engine ────────────────────────────────────────────────

function detectAgent(commit) {
  const detectors = [
    detectClaudeCode,
    detectCursor,
    detectCopilot,
    detectDevin,
    detectAider,
    detectGenericAI,
  ];

  let best = { agentId: "human", confidence: 0, modelVersion: null, signals: [] };

  for (const detect of detectors) {
    const r = detect(commit);
    if (r.matched && r.confidence > best.confidence) {
      best = { agentId: r.agentId, confidence: r.confidence, modelVersion: r.modelVersion, signals: r.signals };
    }
  }

  return best;
}

function detectClaudeCode(c) {
  const signals = [];
  let confidence = 0;
  let modelVersion = null;
  const text = c.trailers + "\n" + c.body;

  const m = text.match(/Co-[Aa]uthored-[Bb]y:\s*[Cc]laude[^<]*<(?:claude@anthropic\.com|noreply@anthropic\.com)>/i);
  if (m) {
    signals.push("co-authored-by-claude-trailer");
    confidence = 0.95;
    const v = m[0].match(/[Cc]laude\s+((?:Opus|Sonnet|Haiku)\s*[\d.]+(?:\s*\([^)]+\))?)/);
    if (v) modelVersion = `Claude ${v[1].trim()}`;
  }
  if (c.body.includes("Generated by Claude Code") || c.body.includes("Generated with Claude Code")) {
    signals.push("claude-code-generation-marker");
    confidence = Math.max(confidence, 0.95);
  }

  return { matched: signals.length > 0, agentId: "claude-code", confidence, modelVersion, signals };
}

function detectCursor(c) {
  const signals = [];
  let confidence = 0;
  const text = c.trailers + "\n" + c.body;

  if (c.author === "cursor[bot]" || c.email.includes("cursor[bot]")) {
    signals.push("cursor-bot-author"); confidence = 0.95;
  }
  if (c.email === "cursoragent@cursor.com" || c.author === "Cursor Agent") {
    signals.push("cursor-agent-author"); confidence = Math.max(confidence, 0.95);
  }
  if (text.match(/Co-[Aa]uthored-[Bb]y:\s*(?:Cursor|Cursor Agent)\s*<cursoragent@cursor\.com>/i)) {
    signals.push("cursor-agent-co-author"); confidence = Math.max(confidence, 0.95);
  }
  if (text.match(/Co-[Aa]uthored-[Bb]y:\s*cursor-agent\s*<cursor-agent@cursor\.sh>/i)) {
    signals.push("cursor-agent-co-author"); confidence = Math.max(confidence, 0.95);
  }
  if (c.body.includes("Applied via @cursor push command")) {
    signals.push("cursor-push-command"); confidence = Math.max(confidence, 0.9);
  }
  if (c.trailers.match(/Made-with:\s*Cursor/i)) {
    signals.push("made-with-cursor-trailer"); confidence = Math.max(confidence, 0.85);
  }

  return { matched: signals.length > 0, agentId: "cursor", confidence, modelVersion: null, signals };
}

function detectCopilot(c) {
  const signals = [];
  let confidence = 0;
  const text = c.trailers + "\n" + c.body;

  const emails = ["copilot@github.com", "175728472+Copilot@users.noreply.github.com", "223556219+Copilot@users.noreply.github.com"];
  for (const email of emails) {
    if (text.includes(email)) { signals.push("copilot-co-authored-trailer"); confidence = 0.95; break; }
  }
  if (c.author === "copilot-swe-agent[bot]" || c.email.includes("198982749+Copilot@users.noreply.github.com")) {
    signals.push("copilot-swe-agent-author"); confidence = Math.max(confidence, 0.95);
  }
  if (c.trailers.match(/Agent-Logs-Url:/i)) {
    signals.push("copilot-agent-logs-trailer"); confidence = Math.max(confidence, 0.9);
  }

  return { matched: signals.length > 0, agentId: "copilot", confidence, modelVersion: null, signals };
}

function detectDevin(c) {
  const signals = [];
  let confidence = 0;

  if (c.email.includes("devin-ai-integration[bot]")) {
    signals.push("devin-bot-author"); confidence = 0.95;
  }
  if (c.author === "Devin AI") {
    signals.push("devin-author-name"); confidence = Math.max(confidence, 0.95);
  }

  return { matched: signals.length > 0, agentId: "devin", confidence, modelVersion: null, signals };
}

function detectAider(c) {
  const signals = [];
  let confidence = 0;
  let modelVersion = null;
  const text = c.trailers + "\n" + c.body;

  const m = text.match(/Co-[Aa]uthored-[Bb]y:\s*aider\s*\(([^)]+)\)\s*<aider@aider\.chat>/i);
  if (m) { signals.push("aider-co-authored-trailer"); confidence = 0.95; modelVersion = m[1].trim(); }
  if (!m && text.includes("aider@aider.chat")) { signals.push("aider-email"); confidence = Math.max(confidence, 0.85); }
  if (c.message.match(/^aider:/i)) { signals.push("aider-message-prefix"); confidence = Math.max(confidence, 0.9); }

  return { matched: signals.length > 0, agentId: "aider", confidence, modelVersion, signals };
}

function detectGenericAI(c) {
  const signals = [];
  let confidence = 0;
  const text = c.trailers + "\n" + c.body;

  const bots = ["dependabot", "renovate", "greenkeeper", "snyk-bot", "mergify"];
  if (bots.some(b => text.toLowerCase().includes(b))) {
    return { matched: false, agentId: "unknown-ai", confidence: 0, modelVersion: null, signals: [] };
  }
  // Word boundaries + same-line only. Without \b the alternation matched
  // substrings inside ordinary text — "ai" inside "gm[ai]l.com", "Cl[ai]re" —
  // flagging human commits as AI.
  if (text.match(/Co-[Aa]uthored-[Bb]y:[^\n]*\b(?:ai|assistant|agent|llm)\b/i)) {
    signals.push("generic-ai-co-author"); confidence = 0.6;
  }
  if (c.body.match(/generated\s+(?:by|with|using)\s+(?:an?\s+)?\b(?:ai|llm|assistant|agent)\b/i)) {
    signals.push("ai-generation-mention-in-body"); confidence = Math.max(confidence, 0.5);
  }

  return { matched: signals.length > 0, agentId: "unknown-ai", confidence, modelVersion: null, signals };
}

// ── Git Parsing ─────────────────────────────────────────────────────

const RS = "<<CODEGOV_RS>>";
const RE = "<<CODEGOV_RE>>";
const FS = "<<CODEGOV_FS>>";
const BS = "<<CODEGOV_BS>>";

function getCommitsInRange(baseSha, headSha) {
  const format = RS + ["%H", "%aI", "%an", "%ae", "%s"].join(FS) + BS + "%b" + BS + "%(trailers)" + RE;
  let output;
  try {
    output = execSync(`git log --format="${format}" --numstat ${baseSha}..${headSha}`, {
      encoding: "utf-8",
      maxBuffer: 50 * 1024 * 1024,
    });
  } catch {
    return [];
  }

  const commits = [];
  for (const block of output.split(RS)) {
    if (!block.includes(RE)) continue;
    const [formatPart, afterEnd] = block.split(RE);
    const bodyParts = formatPart.split(BS);
    if (bodyParts.length < 3) continue;

    const fields = bodyParts[0].trim().split(FS);
    if (fields.length < 5) continue;

    let linesAdded = 0, linesRemoved = 0;
    const filesChanged = [];
    if (afterEnd) {
      for (const line of afterEnd.split("\n")) {
        const m = line.match(/^(\d+|-)\t(\d+|-)\t(.+)$/);
        if (m) {
          linesAdded += m[1] === "-" ? 0 : parseInt(m[1]);
          linesRemoved += m[2] === "-" ? 0 : parseInt(m[2]);
          filesChanged.push(m[3]);
        }
      }
    }

    commits.push({
      hash: fields[0], timestamp: fields[1], author: fields[2],
      email: fields[3], message: fields[4],
      body: (bodyParts[1] || "").trim(),
      trailers: (bodyParts[2] || "").trim(),
      filesChanged, linesAdded, linesRemoved,
    });
  }
  return commits;
}

// ── Comment Formatting ──────────────────────────────────────────────

const AGENT_LABELS = {
  "claude-code": "Claude Code",
  "cursor": "Cursor",
  "copilot": "GitHub Copilot",
  "devin": "Devin",
  "aider": "Aider",
  "unknown-ai": "Unknown AI",
};

// Count only the five branded tools (each matched on a specific signature).
// The generic "unknown-ai" heuristic is excluded from PR counts to avoid false
// positives (e.g. a human co-author on a gmail address).
const BRANDED = new Set(["claude-code", "cursor", "copilot", "devin", "aider"]);

function formatComment(commits, results) {
  const aiResults = results.filter(r => r.confidence > 0.3 && BRANDED.has(r.agentId));
  const total = commits.length;
  const aiCount = aiResults.length;

  if (aiCount === 0) {
    return [
      "### CodeGov: AI Provenance Scan",
      "",
      `Scanned **${total}** commit${total !== 1 ? "s" : ""} in this PR. No AI-authored commits detected.`,
      "",
      "---",
      "*[CodeGov](https://github.com/james-wall/codegov) detects AI-authored commits from git metadata.*",
    ].join("\n");
  }

  const pct = ((aiCount / total) * 100).toFixed(0);

  // Agent breakdown
  const agentCounts = {};
  for (const r of aiResults) {
    agentCounts[r.agentId] = (agentCounts[r.agentId] || 0) + 1;
  }
  const agentSummary = Object.entries(agentCounts)
    .sort((a, b) => b[1] - a[1])
    .map(([id, count]) => `**${AGENT_LABELS[id] || id}** (${count})`)
    .join(", ");

  // Per-commit table
  const rows = aiResults.map(r => {
    const hash = r.hash.slice(0, 7);
    const agent = AGENT_LABELS[r.agentId] || r.agentId;
    const model = r.modelVersion ? ` (${r.modelVersion})` : "";
    const conf = Math.round(r.confidence * 100);
    return `| \`${hash}\` | ${agent}${model} | +${r.linesAdded}/-${r.linesRemoved} | ${conf}% |`;
  });

  return [
    "### CodeGov: AI Provenance Scan",
    "",
    `**${pct}%** of commits in this PR are AI-authored (${aiCount}/${total})`,
    "",
    `Agents: ${agentSummary}`,
    "",
    "| Commit | Agent | Changes | Confidence |",
    "|--------|-------|---------|------------|",
    ...rows,
    "",
    "---",
    "*[CodeGov](https://github.com/james-wall/codegov) detects AI-authored commits from git metadata.*",
  ].join("\n");
}

// ── GitHub API ──────────────────────────────────────────────────────

async function postComment(repo, prNumber, body) {
  const token = process.env.GITHUB_TOKEN;
  const url = `https://api.github.com/repos/${repo}/issues/${prNumber}/comments`;

  // Check for existing CodeGov comment to update instead of spamming
  const existing = await fetch(url, {
    headers: { Authorization: `token ${token}`, Accept: "application/vnd.github+json" },
  }).then(r => r.json());

  const prior = existing.find?.(c => c.body?.includes("### CodeGov: AI Provenance Scan"));

  if (prior) {
    await fetch(`https://api.github.com/repos/${repo}/issues/comments/${prior.id}`, {
      method: "PATCH",
      headers: { Authorization: `token ${token}`, Accept: "application/vnd.github+json", "Content-Type": "application/json" },
      body: JSON.stringify({ body }),
    });
    console.log(`Updated existing comment #${prior.id}`);
  } else {
    await fetch(url, {
      method: "POST",
      headers: { Authorization: `token ${token}`, Accept: "application/vnd.github+json", "Content-Type": "application/json" },
      body: JSON.stringify({ body }),
    });
    console.log("Posted new comment");
  }
}

// ── Main ────────────────────────────────────────────────────────────

async function main() {
  const baseSha = process.env.BASE_SHA;
  const headSha = process.env.HEAD_SHA;
  const repo = process.env.REPO;
  const prNumber = process.env.PR_NUMBER;

  if (!baseSha || !headSha || !repo || !prNumber) {
    console.error("Missing required environment variables. This action must run on pull_request events.");
    process.exit(1);
  }

  // baseSha/headSha are interpolated into a shell command below — require hex SHAs.
  const shaRe = /^[0-9a-fA-F]{7,64}$/;
  if (!shaRe.test(baseSha) || !shaRe.test(headSha)) {
    console.error("BASE_SHA and HEAD_SHA must be hex commit SHAs.");
    process.exit(1);
  }

  console.log(`Scanning commits ${baseSha.slice(0, 7)}..${headSha.slice(0, 7)}`);

  const commits = getCommitsInRange(baseSha, headSha);
  console.log(`Found ${commits.length} commits in PR`);

  const results = commits.map(c => {
    const d = detectAgent(c);
    return { ...d, hash: c.hash, linesAdded: c.linesAdded, linesRemoved: c.linesRemoved };
  });

  const aiCount = results.filter(r => r.confidence > 0.3 && BRANDED.has(r.agentId)).length;
  console.log(`Detected ${aiCount} AI-authored commits`);

  const comment = formatComment(commits, results);
  await postComment(repo, prNumber, comment);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
